-- You should not modify if this have pushed to Github, unless it does serious wrong with the db.
BEGIN TRANSACTION;

-- Generated by Intellij IDEA
create table setting_dg_tmp
(
    id INTEGER
        primary key autoincrement,
    key VARCHAR(200) not null
        unique,
    value TEXT,
    type VARCHAR(20)
);

insert into setting_dg_tmp(id, key, value, type) select id, key, value, type from setting;

drop table setting;

alter table setting_dg_tmp rename to setting;

COMMIT;
