POST http://localhost:3001/api
Authorization: Bearer uk1_1HaQRETls-E5KlhB6yCtf8WJRW57KwFMuKkya-Tj
Content-Type: application/json

{
    "action": "getPushExample",
    "params": [
        "javascript-fetch"
    ]
}
###
