# DON'T UPDATE TO alpine3.13, 1.14, see #41.
FROM node:14-alpine3.12 AS build
WORKDIR /app

COPY . .
RUN npm install --legacy-peer-deps && \
    npm run build && \
    npm prune --production && \
    chmod +x /app/extra/entrypoint.sh


FROM node:14-alpine3.12 AS release

ARG BUILD_DATE

LABEL org.opencontainers.image.authors='Louis Lam' \
      org.opencontainers.image.url='https://uptime.kuma.pet' \
      org.opencontainers.image.documentation='https://github.com/louislam/uptime-kuma/wiki' \
      org.opencontainers.image.source='https://github.com/louislam/uptime-kuma.git' \
      org.opencontainers.image.vendor='Louis Lam' \
      org.opencontainers.image.licenses='MIT License' \
      org.opencontainers.image.title="Uptime Kuma" \
      org.opencontainers.image.description="Self-hosted uptime monitoring tool with notifications" \
      org.opencontainers.image.created=$BUILD_DATE

WORKDIR /app

# Install apprise, iputils for non-root ping, setpriv
RUN apk add --no-cache iputils setpriv python3 py3-cryptography py3-pip py3-six py3-yaml py3-click py3-markdown py3-requests py3-requests-oauthlib && \
    pip3 --no-cache-dir install apprise && \
    rm -rf /root/.cache

# Copy app files from build layer
COPY --from=build /app /app

EXPOSE 3001
VOLUME ["/app/data"]
HEALTHCHECK --interval=60s --timeout=30s --start-period=180s --retries=5 CMD node extra/healthcheck.js
ENTRYPOINT ["extra/entrypoint.sh"]
CMD ["node", "server/server.js"]

FROM release AS nightly
RUN npm run mark-as-nightly
