const providerCatalog = [
    {
        id: "openai",
        name: "OpenAI API",
        company: "OpenAI",
        endpoint: "api.openai.com/v1",
        group: "International",
        models: ["gpt-4.1", "gpt-4o", "o3-mini"],
    },
    {
        id: "claude",
        name: "Claude API / Anthropic",
        company: "Anthropic",
        endpoint: "api.anthropic.com/v1",
        group: "International",
        models: ["claude-3.5-sonnet", "claude-3-opus", "claude-3-haiku"],
    },
    {
        id: "gemini",
        name: "Gemini API / Google",
        company: "Google",
        endpoint: "generativelanguage.googleapis.com",
        group: "International",
        models: ["gemini-1.5-pro", "gemini-1.5-flash", "embedding-001"],
    },
    {
        id: "deepseek",
        name: "DeepSeek API",
        company: "DeepSeek",
        endpoint: "api.deepseek.com/v1",
        group: "China",
        models: ["deepseek-chat", "deepseek-reasoner", "deepseek-coder"],
    },
    {
        id: "kimi",
        name: "Kimi API / Moonshot AI",
        company: "Moonshot AI",
        endpoint: "api.moonshot.cn/v1",
        group: "China",
        models: ["moonshot-v1-8k", "moonshot-v1-32k", "moonshot-v1-128k"],
    },
    {
        id: "minimax",
        name: "MiniMax API",
        company: "MiniMax",
        endpoint: "api.minimax.chat/v1",
        group: "China",
        models: ["abab6.5s-chat", "abab6.5g-chat", "embo-01"],
    },
    {
        id: "zhipu",
        name: "Zhipu GLM API / 智谱 AI",
        company: "智谱 AI",
        endpoint: "open.bigmodel.cn/api/paas/v4",
        group: "China",
        models: ["glm-4-plus", "glm-4-air", "embedding-3"],
    },
    {
        id: "seedance",
        name: "SeeDance API",
        company: "SeeDance",
        endpoint: "api.seedance.com/v1",
        group: "China",
        models: ["seedance-pro", "seedance-lite", "seedance-vision"],
    },
    {
        id: "grok",
        name: "Grok API / xAI",
        company: "xAI",
        endpoint: "api.x.ai/v1",
        group: "International",
        models: ["grok-2", "grok-2-mini", "grok-vision"],
    },
];

const baseProviderState = {
    openai: { routeWeight: 22, latencyP50: 286, latencyP95: 718, errorRate: 0.08, costUnit: 0.000016, requests: 183420, tokens: 238400000 },
    claude: { routeWeight: 18, latencyP50: 342, latencyP95: 864, errorRate: 0.10, costUnit: 0.000021, requests: 148960, tokens: 196700000 },
    gemini: { routeWeight: 16, latencyP50: 318, latencyP95: 796, errorRate: 0.11, costUnit: 0.000012, requests: 131280, tokens: 172900000 },
    deepseek: { routeWeight: 12, latencyP50: 254, latencyP95: 642, errorRate: 0.07, costUnit: 0.000006, requests: 104760, tokens: 143600000 },
    kimi: { routeWeight: 10, latencyP50: 272, latencyP95: 690, errorRate: 0.09, costUnit: 0.000006, requests: 92480, tokens: 126400000 },
    minimax: { routeWeight: 8, latencyP50: 298, latencyP95: 744, errorRate: 0.10, costUnit: 0.000007, requests: 78840, tokens: 102200000 },
    zhipu: { routeWeight: 7, latencyP50: 310, latencyP95: 772, errorRate: 0.12, costUnit: 0.000007, requests: 69160, tokens: 91700000 },
    seedance: { routeWeight: 4, latencyP50: 328, latencyP95: 814, errorRate: 0.13, costUnit: 0.000009, requests: 37120, tokens: 48600000 },
    grok: { routeWeight: 3, latencyP50: 362, latencyP95: 910, errorRate: 0.14, costUnit: 0.000014, requests: 28640, tokens: 38200000 },
};

const scenarioFrames = [
    {
        stage: "全链路稳定",
        stageHint: "全链路稳定",
        health: "Healthy",
        activeIncidents: 0,
        routeWeights: { openai: 22, claude: 18, gemini: 16, deepseek: 12, kimi: 10, minimax: 8, zhipu: 7, seedance: 4, grok: 3 },
        deltas: { latency: {}, error: {}, status: {} },
        summaryText: "TokenFleet 数据中台保持多路 API 接入稳定，可信计量、重试去重、失败免计和供应商对账链路均处于稳定采样状态。",
    },
    {
        stage: "Claude 延迟升高",
        stageHint: "Claude延迟升高",
        health: "Degraded",
        activeIncidents: 1,
        routeWeights: { openai: 23, claude: 18, gemini: 16, deepseek: 12, kimi: 10, minimax: 8, zhipu: 7, seedance: 4, grok: 2 },
        deltas: { latency: { claude: 340 }, error: { claude: 0.12 }, status: { claude: "degraded" } },
        incident: ["Claude API / Anthropic", "P95 延迟超过阈值", "Claude API 延迟升高，网关提高采样频率并准备切流。"],
        summaryText: "Claude 链路延迟升高后，数据中台继续保留请求链路解释，计量差异进入快速收敛窗口。",
    },
    {
        stage: "降低 Claude 路由权重",
        stageHint: "Claude权重下调",
        health: "Degraded",
        activeIncidents: 1,
        routeWeights: { openai: 25, claude: 9, gemini: 18, deepseek: 14, kimi: 12, minimax: 8, zhipu: 7, seedance: 4, grok: 3 },
        deltas: { latency: { claude: 300 }, error: { claude: 0.10 }, status: { claude: "degraded" } },
        incident: ["Gateway", "Claude 路由权重已自动下调", "高优先级请求转入低延迟模型池，入口 SLA 保持稳定。"],
        summaryText: "路由器降低 Claude 权重后，实际流量以轻微滞后方式跟随策略权重变化，失败请求继续免计。",
    },
    {
        stage: "DeepSeek 与 Kimi 承接流量",
        stageHint: "国产模型承接",
        health: "Degraded",
        activeIncidents: 1,
        routeWeights: { openai: 23, claude: 8, gemini: 17, deepseek: 18, kimi: 15, minimax: 8, zhipu: 7, seedance: 3, grok: 1 },
        deltas: { latency: { claude: 220, deepseek: -14, kimi: -12 }, error: { claude: 0.08 }, status: { claude: "degraded" } },
        incident: ["DeepSeek API, Kimi API / Moonshot AI", "国产模型池承接流量提升", "DeepSeek 与 Kimi 承接更多批量任务与中文任务。"],
        summaryText: "国产模型池开始承接更多工作流节点，成本、延迟、中文能力和稳定性策略共同参与调度决策。",
    },
    {
        stage: "SeeDance 维护",
        stageHint: "SeeDance维护中",
        health: "Degraded",
        activeIncidents: 2,
        routeWeights: { openai: 24, claude: 8, gemini: 18, deepseek: 18, kimi: 15, minimax: 9, zhipu: 7, seedance: 0, grok: 1 },
        deltas: { latency: { claude: 160 }, error: { claude: 0.06 }, status: { claude: "degraded", seedance: "maintenance" } },
        incident: ["SeeDance API", "计划维护窗口已开始", "SeeDance 权重置零，多模态请求转交到可用模型池。"],
        summaryText: "SeeDance 维护窗口被隔离，网关保留健康探测，计量对账不受维护窗口影响。",
    },
    {
        stage: "Gemini 5xx 波动",
        stageHint: "Gemini错误波动",
        health: "Degraded",
        activeIncidents: 3,
        routeWeights: { openai: 27, claude: 8, gemini: 10, deepseek: 18, kimi: 15, minimax: 9, zhipu: 12, seedance: 0, grok: 1 },
        deltas: { latency: { claude: 120, gemini: 106 }, error: { gemini: 1.72, claude: 0.04 }, status: { claude: "degraded", gemini: "degraded", seedance: "maintenance" } },
        incident: ["Gemini API / Google", "短时 5xx 错误率波动", "Gemini 5xx 波动触发幂等重试、失败免计和熔断转交。"],
        summaryText: "Gemini 5xx 波动期间，失败请求不进入计费用量，重试链路按幂等键去重并可解释。",
    },
    {
        stage: "成本守护触发",
        stageHint: "成本守护触发",
        health: "Degraded",
        activeIncidents: 3,
        routeWeights: { openai: 21, claude: 7, gemini: 8, deepseek: 24, kimi: 19, minimax: 10, zhipu: 10, seedance: 0, grok: 1 },
        deltas: { latency: { claude: 80, gemini: 78 }, error: { gemini: 0.82 }, status: { claude: "degraded", gemini: "degraded", seedance: "maintenance" } },
        incident: ["Gateway", "成本守护策略已触发", "批量任务转向 DeepSeek、Kimi、MiniMax 与 GLM，降低单位算力成本。"],
        summaryText: "成本守护触发后，Agent 批量节点转向国产模型池，高优先级请求仍保留质量阈值。",
    },
    {
        stage: "Claude 恢复",
        stageHint: "Claude延迟恢复",
        health: "Recovering",
        activeIncidents: 2,
        routeWeights: { openai: 22, claude: 13, gemini: 9, deepseek: 22, kimi: 18, minimax: 9, zhipu: 8, seedance: 0, grok: 1 },
        deltas: { latency: { claude: 24, gemini: 42 }, error: { gemini: 0.34 }, status: { gemini: "degraded", seedance: "maintenance" } },
        incident: ["Claude API / Anthropic", "延迟恢复到健康区间", "Claude 连续健康采样后按阶梯策略恢复权重。"],
        summaryText: "Claude 延迟恢复后，权重按阶梯恢复，避免瞬时回流，同时保持高可用指标继续回升。",
    },
    {
        stage: "网关整体恢复稳定",
        stageHint: "整体恢复稳定",
        health: "Healthy",
        activeIncidents: 0,
        routeWeights: { openai: 22, claude: 16, gemini: 15, deepseek: 16, kimi: 13, minimax: 8, zhipu: 7, seedance: 2, grok: 1 },
        deltas: { latency: {}, error: {}, status: {} },
        incident: ["Gateway", "联合处置策略完成", "延迟、错误率、维护和成本事件完成联合处置。"],
        summaryText: "TokenFleet 数据中台完成一次完整策略闭环，可信计量、路由调度、Agent 调度和供应商对账均回到稳定基线。",
    },
];

module.exports = {
    baseProviderState,
    providerCatalog,
    scenarioFrames,
};
