name: "❓ Ask for help"
description: "Submit any question related to Uptime Kuma"
#title: "[Help] "
labels: [help]
body:
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "⚠️ Please verify that this question has NOT been raised before."
      description: "Search in the issues sections by clicking [HERE](https://github.com/louislam/uptime-kuma/issues?q=)"
      options:
        - label: "I checked and didn't find similar issue"
          required: true
  - type: checkboxes
    attributes:
      label: "🛡️ Security Policy"
      description: Please review the security policy before reporting security related issues/bugs.
      options:
        - label: I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)
          required: true
  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: "📝 Describe your problem"
      description: "Please walk us through it step by step. Include all important details and add screenshots where appropriate"
      placeholder: "Describe what are you asking for..."
  - type: textarea
    id: error-msg
    validations:
      required: false
    attributes:
      label: "📝 Error Message(s) or Log"
  - type: input
    id: uptime-kuma-version
    attributes:
      label: "🐻 Uptime-Kuma Version"
      description: "Which version of Uptime-Kuma are you running? Please do NOT provide the docker tag such as latest or 1"
      placeholder: "Ex. 1.10.0"
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: "💻 Operating System and Arch"
      description: "Which OS is your server/device running on? (For Replit, please do not report this bug)"
      placeholder: "Ex. Ubuntu 20.04 x86"
    validations:
      required: true
  - type: input
    id: browser-vendor
    attributes:
      label: "🌐 Browser"
      description: "Which browser are you running on? (For Replit, please do not report this bug)"
      placeholder: "Ex. Google Chrome 95.0.4638.69"
    validations:
      required: true
  - type: textarea
    id: deployment-info
    attributes:
      label: "🖥️ Deployment Environment"
      description: |
        examples:
          - **Runtime**: Docker 20.10.9 / nodejs 14.18.0 / K8S via ... v1.3.3 / ..
          - **Database**: sqlite/embedded mariadb/external mariadb
          - **Filesystem used to store the database on**: Windows/ZFS/btrfs/NFSv3 on a SSD/HDD/eMMC
          - **number of monitors**: 42
      value: |
        - Runtime: 
        - Database: 
        - Filesystem used to store the database on: 
        - number of monitors: 
    validations:
      required: true
