---
name: ❓ Ask for help
description: |
  Submit any question related to Uptime Kuma
#title: "[Help]"
labels: ["help"]
body:
  - type: markdown
    attributes:
      value: |
        🚫 **We kindly ask you to refrain from pinging maintainers unless absolutely necessary. Pings are reserved for critical/urgent issues that require immediate attention.**

        **Why**: Reserving pings for urgent matters ensures maintainers can prioritize critical tasks effectively

  - type: checkboxes
    id: no-duplicate-question
    attributes:
      label: ⚠️ Please verify that your question has not already been reported
      description: |
        To avoid duplicate reports, please search for any existing issues before submitting a new one. You can find the list of existing issues **[HERE](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue%20sort%3Acreated-desc%20)**.
      options:
        - label: |
            I have searched the [existing issues](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue%20sort%3Acreated-desc%20) and found no similar reports.
          required: true

  - type: checkboxes
    id: security-policy
    attributes:
      label: 🛡️ Security Policy
      description: |
        Please review and acknowledge the Security Policy before reporting any security-related issues or bugs. You can find the full Security Policy **[HERE](https://github.com/louislam/uptime-kuma/security/policy)**.
      options:
        - label: |
            I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).
          required: true

  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: 📝 Describe your problem
      description: |
        Please walk us through it step by step. Include all important details and add screenshots where appropriate
      placeholder: |
        Describe what are you asking for ...

  - type: textarea
    id: error-msg
    attributes:
      label: 📝 Error Message(s) or Log
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash session
    validations:
      required: false

  - type: input
    id: uptime-kuma-version
    attributes:
      label: 🐻 Uptime-Kuma Version
      description: |
        What version of Uptime-Kuma are you running? Please do not provide Docker tags like `latest` or `1`.
      placeholder: |
        e.g., 1.23.16 or 2.0.0-beta.2
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: 💻 Operating System and Arch
      description: |
        Which OS is your server/device running on? (For Replit, please do not report this bug)
      placeholder: |
        e.g., Ubuntu Server 24.04.2 LTS (GNU/Linux 6.8.0-55-generic x86_64)
    validations:
      required: true

  - type: input
    id: browser-vendor
    attributes:
      label: 🌐 Browser
      description: |
        Which browser are you running on? (For Replit, please do not report this bug)
      placeholder: |
        e.g., Google Chrome 134.0.6998.183 (Official Build) (64-bit)
    validations:
      required: true

  - type: textarea
    id: deployment-info
    attributes:
      label: 🖥️ Deployment Environment
      description: |
        Provide details about the deployment environment, including runtime components, databases, and storage configurations. This will
        help assess the infrastructure and identify any potential compatibility requirements.

        **Remove any fields that do not apply to your setup.**
      value: |
        - **Runtime Environment**:
          - Docker: Version `X.X.X` (Build `Y.Y.Y`)
          - Docker Compose: Version `X.X.X`
          - Portainer (BE/CE): Version `X.X.X` (LTS: Yes/No)
          - MariaDB: Version `X.X.X` (LTS: Yes/No)
          - Node.js: Version `X.X.X` (LTS: Yes/No)
          - Kubernetes (K3S/K8S): Version `X.X.X` (LTS: Yes/No, via `[method/tool]`)
        - **Database**:
          - SQLite: Embedded
          - MariaDB: Embedded/External
        - **Database Storage**:
          - **Filesystem**:
            - Linux: ext4/XFS/Btrfs/ZFS/F2FS
            - macOS: APFS/ HFS+
            - Windows: NTFS/ReFS
          - **Storage Medium**: HDD/eMMC/SSD/NVMe
        - **Uptime Kuma Setup**:
          - Number of monitors: `X`
    validations:
      required: true
