name: "🐛 Bug Report"
description: "Submit a bug report to help us improve"
#title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    id: related-issues
    validations:
      required: true
    attributes:
      label: "📑 I have found these related issues/pull requests"
      description: "Search related issues by clicking [HERE](https://github.com/louislam/uptime-kuma/issues?q=) and explain what the difference between them or explain that you are unable to find any related issues"
      placeholder: "Related to #1 by also touching the ... system. They should not be merged because ..."
  - type: checkboxes
    attributes:
      label: "🛡️ Security Policy"
      description: Please review the security policy before reporting security related issues/bugs.
      options:
        - label: I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)
          required: true
  - type: textarea
    id: description
    validations:
      required: false
    attributes:
      label: "Description"
      description: "You could also upload screenshots"
  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: "👟 Reproduction steps"
      description: "How do you trigger this bug? Please walk us through it step by step. Include all important details and add screenshots where appropriate"
      placeholder: "..."
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: "👀 Expected behavior"
      description: "What did you think would happen?"
      placeholder: "..."
  - type: textarea
    id: actual-behavior
    validations:
      required: true
    attributes:
      label: "😓 Actual Behavior"
      description: "What actually happen?"
      placeholder: "..."
  - type: input
    id: uptime-kuma-version
    attributes:
      label: "🐻 Uptime-Kuma Version"
      description: "Which version of Uptime-Kuma are you running? Please do NOT provide the docker tag such as latest or 1"
      placeholder: "Ex. 1.10.0"
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: "💻 Operating System and Arch"
      description: "Which OS is your server/device running on? (For Replit, please do not report this bug)"
      placeholder: "Ex. Ubuntu 20.04 x64 "
    validations:
      required: true
  - type: input
    id: browser-vendor
    attributes:
      label: "🌐 Browser"
      description: "Which browser are you running on?"
      placeholder: "Ex. Google Chrome 95.0.4638.69"
    validations:
      required: true
  - type: textarea
    id: deployment-info
    attributes:
      label: "🖥️ Deployment Environment"
      description: |
        examples:
          - **Runtime**: Docker 20.10.9 / nodejs 18.17.1 / K8S via ... v1.3.3 / ..
          - **Database**: sqlite/embedded mariadb/external mariadb
          - **Filesystem used to store the database on**: Windows/ZFS/btrfs/NFSv3 on a SSD/HDD/eMMC
          - **number of monitors**: 42
      value: |
        - Runtime: 
        - Database: 
        - Filesystem used to store the database on: 
        - number of monitors: 
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "📝 Relevant log output"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
