name: 🚀 Feature Request
description: "Submit a proposal for a new feature"
#title: "[Feature] "
labels: [feature-request]
body:
  - type: textarea
    id: related-issues
    validations:
      required: true
    attributes:
      label: "📑 I have found these related issues/pull requests"
      description: "Search related issues by clicking [HERE](https://github.com/louislam/uptime-kuma/issues?q=) and explain what the difference between them or explain that you are unable to find any related issues"
      placeholder: "Related to #1 by also touching the ... system. They should not be merged because ..."
  - type: dropdown
    id: feature-area
    attributes:
      label: "🏷️ Feature Request Type"
      description: "What kind of feature request is this?"
      multiple: true
      options:
        - API / automation options
        - New notification-provider
        - Change to existing notification-provider
        - New monitor
        - Change to existing monitor
        - Dashboard
        - Status-page
        - Maintenance
        - Deployment
        - Certificate expiry
        - Settings
        - Other
    validations:
      required: true
  - type: textarea
    id: feature-description
    validations:
      required: true
    attributes:
      label: "🔖 Feature description"
      description: "A clear and concise description of what the feature request is."
      placeholder: "You should add ..."
  - type: textarea
    id: solution
    validations:
      required: true
    attributes:
      label: "✔️ Solution"
      description: "A clear and concise description of what you want to happen."
      placeholder: "In my use-case, ..."
  - type: textarea
    id: alternatives
    validations:
      required: false
    attributes:
      label: "❓ Alternatives"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "I have considered ..."
  - type: textarea
    id: additional-context
    validations:
      required: false
    attributes:
      label: "📝 Additional Context"
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "..."
