FROM louislam/uptime-kuma:base-alpine AS build_server
WORKDIR /app

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1

# Cache docker layers, faster development, less bandwidth much wauw
COPY package.json .
COPY package-lock.json .
RUN npm ci --production

# Copy all over
COPY . .
RUN chmod +x extra/entrypoint.sh

FROM louislam/uptime-kuma:base-alpine AS build_app
WORKDIR /app

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1

COPY . .
RUN npm ci && npm run build

FROM louislam/uptime-kuma:base-alpine AS release
WORKDIR /app

# Copy app files from build layer
COPY --from=build_server /app /app
COPY --from=build_app /app/dist /app/dist

EXPOSE 3001
VOLUME ["/app/data"]
HEALTHCHECK --interval=60s --timeout=30s --start-period=180s --retries=5 CMD node extra/healthcheck.js
ENTRYPOINT ["/usr/bin/dumb-init", "--", "extra/entrypoint.sh"]
CMD ["node", "server/server.js"]


FROM release AS nightly
RUN npm run mark-as-nightly
