apiVersion: v2
name: uptime-kuma
description: A Helm chart for Uptime Kuma - A fancy self-hosted monitoring tool
type: application
version: 0.1.0
appVersion: "1.23.13"
keywords:
  - monitoring
  - uptime
  - health-check
home: https://uptime.kuma.pet/
sources:
  - https://github.com/louislam/uptime-kuma
maintainers:
  - name: uptime-kuma
    url: https://github.com/louislam/uptime-kuma
