name: autofix.ci

on:
  push:
    branches: ["master", "1.23.X"]
  pull_request:
permissions: {}

jobs:
  autofix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { persist-credentials: false }

      #    Tempoary disable until we understand TanStack npm supply-chain compromise
      #      - name: Cache/Restore node_modules
      #        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      #        id: node-modules-cache
      #        with:
      #          path: node_modules
      #          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Auto-fix JavaScript/Vue linting issues
        run: npm run lint-fix:js
        continue-on-error: true

      - name: Auto-fix CSS/SCSS linting issues
        run: npm run lint-fix:style
        continue-on-error: true

      - name: Auto-format code with Prettier
        run: npm run fmt
        continue-on-error: true

      - name: Compile TypeScript
        run: npm run tsc
        continue-on-error: true

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
