name: Build PR Test Docker Image

on:
  schedule:
    # Runs at 2:00 AM UTC on the 1st of every month
    - cron: "0 2 1 * *"
  workflow_dispatch: # Allow manual trigger

permissions: {}

jobs:
  build-docker-pr-test:
    # Only run on the original repository, not on forks
    if: github.repository == 'louislam/uptime-kuma'
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { persist-credentials: false }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4.3.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Use Node.js 26
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26

      - name: Build and push pr-test2
        run: node --run build-docker-pr-test
