name: Close Incorrect Issue

on:
  issues:
    types: [opened]
permissions: {}

jobs:
  close-incorrect-issue:
    runs-on: ${{ matrix.os }}
    permissions:
      issues: write

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { persist-credentials: false }

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Close incorrect issue
        run: node extra/close-incorrect-issue.js ${{ secrets.GITHUB_TOKEN }} ${{ github.event.issue.number }} "$ISSUE_USER_LOGIN"
        env:
          ISSUE_USER_LOGIN: ${{ github.event.issue.user.login }}
