name: Close Incorrect Issue

on:
  issues:
    types: [opened]
permissions: {}

jobs:
  close-incorrect-issue:
    runs-on: ubuntu-slim
    permissions:
      issues: write
    steps:
      - name: Close incorrect issue
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            try {
                const username = context.payload.issue.user.login;

                const labels = (
                    await github.rest.issues.listLabelsOnIssue({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                    })
                ).data.map(({ name }) => name);

                if (labels.length === 0) {
                    console.log("Bad format here");

                    await github.rest.issues.addLabels({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        labels: ["invalid-format"],
                    });

                    // Add the issue closing comment
                    await github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        body: `@${username}: Hello! :wave:\n\nThis issue is being automatically closed because it does not follow the issue template. Please **DO NOT open blank issues and use our [issue-templates](https://github.com/louislam/uptime-kuma/issues/new/choose) instead**.\nBlank Issues do not contain the context necessary for a good discussions.`,
                    });

                    // Close the issue
                    await github.rest.issues.update({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        state: "closed",
                    });
                } else {
                    console.log("Pass!");
                }
            } catch (e) {
                console.log(e);
            }
