name: validate
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - 1.23.X
      - 3.0.X
  workflow_dispatch:
permissions: {}

jobs:
  json-yaml-validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # enable write permissions for pull request comments
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { persist-credentials: false }

      - name: json-yaml-validate
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@9dbc6e6ff950c53200156e8afbc16ef1355f1c8d # v5.0.1
        with:
          comment: "true" # enable comment mode
          exclude_file: ".github/config/exclude.txt" # gitignore style file for exclusions

  # General validations
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { persist-credentials: false }
      - name: Use Node.js 25
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 25

      - name: Validate language JSON files
        run: node ./extra/check-lang-json.js

      - name: Validate knex migrations filename
        run: node ./extra/check-knex-filenames.mjs

      - name: Validate package.json
        run: node ./extra/check-package-json.mjs
